version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo-dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
        - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-ui-dev
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  usersapi:
    image: ayushl33t/users-api:latest
    ports:
      - 8000:8000
    environment: 
        DB_URI: mongo
        DB_USER: root
        DB_PASS: admin
  postsapi:
    image: ayushl33t/posts-api:latest
    ports:
      - 8001:8001
    environment:
        USER_URI: http://usersapi:8000/users
        DB_URI: mongo
        DB_USER: root
        DB_PASS: admin